version: '3.8'

services:
  cli-mycontainer:
    container_name: cli-mycontainer
    build: 
      context: .
      dockerfile: dockerfile
    depends_on:
      mysql-cli-mycontainer:
        condition: service_healthy

  mysql-cli-mycontainer:
    container_name: mysql-cli-mycontainer
    image: mysql:8.0.33
    ports:
      - "3302:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "alwi09"
      MYSQL_PASSWORD: "alwiirfani091199"
      MYSQL_DATABASE: "cli_scrappingwiki"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10